### PR TITLE
Rebase to navigation2/master and make general improvements

### PR DESCRIPTION
**Pull request by naiveHobo**
- Added ```time_left``` feedback in ```Wait.action```
- Added ```euclidean_distance``` utility function in ```nav2_utils``` which is used everywhere where distance is calculated
- Fixes a couple of runtime errors in ```nav2_controller```

### CODE REVIEW

**Comment by naiveHobo** [comment]
@SteveMacenski should I open a new PR on navigation2 or does this work?

**Comment by SteveMacenski** [comment]
I'm really confused - what is this?

**Comment by SteveMacenski** [comment]
Ah this is your updated PR on mine.

You can just submit a PR directly to Nav2 and we can just close mine

**Comment by SteveMacenski** [comment]
Though, because this is so old, you need to rebase to master, rather than pulling in, if that's what you did. We cannot enter that many redundant commits and changes to master

**Comment by naiveHobo** [comment]
> I'm really confused - what is this?

Aha, sorry! I can imagine this came out of nowhere.

**Pull request closed without merging**
